export const countries = [
    { code: 'AD', label: 'Андорра', phone: '376' },
    { code: 'AE', label: 'Объединенные Арабские Эмираты', phone: '971' },
    { code: 'AF', label: 'Афганистан', phone: '93' },
    { code: 'AG', label: 'Антигуа и Барбуда', phone: '1-268' },
    { code: 'AI', label: 'Англия', phone: '1-264' },
    { code: 'AL', label: 'Албания', phone: '355' },
    { code: 'AM', label: 'Армения', phone: '374' },
    { code: 'AO', label: 'Ангола', phone: '244' },
    { code: 'AQ', label: 'Антарктика', phone: '672' },
    { code: 'AR', label: 'Аргентина', phone: '54' },
    { code: 'AS', label: 'Американское Самоа', phone: '1-684' },
    { code: 'AT', label: 'Австрия', phone: '43' },
    { code: 'AU', label: 'Австралия', phone: '61', suggested: true },
    { code: 'AW', label: 'Аруба', phone: '297' },
    { code: 'AX', label: 'Алландские острова', phone: '358' },
    { code: 'AZ', label: 'Азербайджан', phone: '994' },
    { code: 'BA', label: 'Босния и Герцеговина', phone: '387' },
    { code: 'BB', label: 'Барбадос', phone: '1-246' },
    { code: 'BD', label: 'Бангладеш', phone: '880' },
    { code: 'BE', label: 'Бельгия', phone: '32' },
    { code: 'BF', label: 'Буркина-Фасо', phone: '226' },
    { code: 'BG', label: 'Болгария', phone: '359' },
    { code: 'BH', label: 'Бахрейн', phone: '973' },
    { code: 'BI', label: 'Бурунди', phone: '257' },
    { code: 'BJ', label: 'Бенин', phone: '229' },
    { code: 'BL', label: 'Сен-Бартелеми', phone: '590' },
    { code: 'BM', label: 'Бермудские острова', phone: '1-441' },
    { code: 'BN', label: 'Бруней', phone: '673' },
    { code: 'BO', label: 'Боливия', phone: '591' },
    { code: 'BR', label: 'Бразилия', phone: '55' },
    { code: 'BS', label: 'Багамы', phone: '1-242' },
    { code: 'BT', label: 'Бутан', phone: '975' },
    { code: 'BV', label: 'Остров Буве', phone: '47' },
    { code: 'BW', label: 'Ботсвана', phone: '267' },
    { code: 'BY', label: 'Беларусь', phone: '375' },
    { code: 'BZ', label: 'Белиз', phone: '501' },
    { code: 'CA', label: 'Канада', phone: '1', suggested: true },
    { code: 'CC', label: 'Кокосовые острова', phone: '61' },
    { code: 'CD', label: 'Демократическая Республика Конго', phone: '243' },
    { code: 'CF', label: 'Центральноафриканская Республика', phone: '236' },
    { code: 'CG', label: 'Республика Конго', phone: '242' },
    { code: 'CH', label: 'Швейцария', phone: '41' },
    { code: 'CI', label: "Кот-д'Ивуар", phone: '225' },
    { code: 'CK', label: 'Острова Кука', phone: '682' },
    { code: 'CL', label: 'Чили', phone: '56' },
    { code: 'CM', label: 'Камерун', phone: '237' },
    { code: 'CN', label: 'Китай', phone: '86' },
    { code: 'CO', label: 'Колумбия', phone: '57' },
    { code: 'CR', label: 'Коста-Рика', phone: '506' },
    { code: 'CU', label: 'Куба', phone: '53' },
    { code: 'CV', label: 'Кабо-Верде', phone: '238' },
    { code: 'CW', label: 'Кюрасао', phone: '599' },
    { code: 'CX', label: 'Остров Рождества', phone: '61' },
    { code: 'CY', label: 'Кипр', phone: '357' },
    { code: 'CZ', label: 'Чешская Республика', phone: '420' },
    {
      code: 'DE',
      label: 'Германия',
      phone: '49',
      suggested: true,
    },
    { code: 'DJ', label: 'Джибути', phone: '253' },
    { code: 'DK', label: 'Дания', phone: '45' },
    { code: 'DM', label: 'Доминика', phone: '1-767' },
    {
      code: 'DO',
      label: 'Доминиканская Республика',
      phone: '1-809',
    },
    { code: 'DZ', label: 'Алжир', phone: '213' },
    { code: 'EC', label: 'Эквадор', phone: '593' },
    { code: 'EE', label: 'Эстония', phone: '372' },
    { code: 'EG', label: 'Египет', phone: '20' },
    { code: 'EH', label: 'Западная Сахара', phone: '212' },
    { code: 'ER', label: 'Эритрея', phone: '291' },
    { code: 'ES', label: 'Испания', phone: '34' },
    { code: 'ET', label: 'Эфиопия', phone: '251' },
    { code: 'FI', label: 'Финляндия', phone: '358' },
    { code: 'FJ', label: 'Фиджи', phone: '679' },
    {
      code: 'FK',
      label: 'Фолклендские острова (Мальвинские)',
      phone: '500',
    },
    {
      code: 'FM',
      label: 'Микронезия, Федеративные Штаты',
      phone: '691',
    },
    { code: 'FO', label: 'Фарерские острова', phone: '298' },
    {
      code: 'FR',
      label: 'Франция',
      phone: '33',
      suggested: true,
    },
    { code: 'GA', label: 'Габон', phone: '241' },
    { code: 'GB', label: 'Соединенное Королевство', phone: '44' },
    { code: 'GD', label: 'Гренада', phone: '1-473' },
    { code: 'GE', label: 'Грузия', phone: '995' },
    { code: 'GF', label: 'Французская Гвиана', phone: '594' },
    { code: 'GG', label: 'Гернси', phone: '44' },
    { code: 'GH', label: 'Гана', phone: '233' },
    { code: 'GI', label: 'Гибралтар', phone: '350' },
    { code: 'GL', label: 'Гренландия', phone: '299' },
    { code: 'GM', label: 'Гамбия', phone: '220' },
    { code: 'GN', label: 'Гвинея', phone: '224' },
    { code: 'GP', label: 'Гваделупа', phone: '590' },
    { code: 'GQ', label: 'Экваториальная Гвинея', phone: '240' },
    { code: 'GR', label: 'Греция', phone: '30' },
    {
      code: 'GS',
      label: 'Южная Джорджия и Южные Сандвичевы острова',
      phone: '500',
    },
    { code: 'GT', label: 'Гватемала', phone: '502' },
    { code: 'GU', label: 'Гуам', phone: '1-671' },
    { code: 'GW', label: 'Гвинея-Бисау', phone: '245' },
    { code: 'GY', label: 'Гайана', phone: '592' },
    { code: 'HK', label: 'Гонконг', phone: '852' },
    { code: 'HM', label: 'Остров Херд и острова Макдональд', phone: '672' },
    { code: 'HN', label: 'Гондурас', phone: '504' },
    { code: 'HR', label: 'Хорватия', phone: '385' },
    { code: 'HT', label: 'Гаити', phone: '509' },
    { code: 'HU', label: 'Венгрия', phone: '36' },
    { code: 'ID', label: 'Индонезия', phone: '62' },
    { code: 'IE', label: 'Ирландия', phone: '353' },
    { code: 'IL', label: 'Израиль', phone: '972' },
    { code: 'IM', label: 'Остров Мэн', phone: '44' },
    { code: 'IN', label: 'Индия', phone: '91' },
    {
      code: 'IO',
      label: 'Британская территория в Индийском океане',
      phone: '246',
    },
    { code: 'IQ', label: 'Ирак', phone: '964' },
    { code: 'IR', label: 'Иран, Исламская Республика', phone: '98' },
    { code: 'IS', label: 'Исландия', phone: '354' },
    { code: 'IT', label: 'Италия', phone: '39' },
    { code: 'JE', label: 'Джерси', phone: '44' },
    { code: 'JM', label: 'Ямайка', phone: '1-876' },
    { code: 'JO', label: 'Иордания', phone: '962' },
    { code: 'JP', label: 'Япония', phone: '81', suggested: true },
    { code: 'KE', label: 'Кения', phone: '254' },
    { code: 'KG', label: 'Кыргызстан', phone: '996' },
    { code: 'KH', label: 'Камбоджа', phone: '855' },
    { code: 'KI', label: 'Кирибати', phone: '686' },
    { code: 'KM', label: 'Коморские острова', phone: '269' },
    { code: 'KN', label: 'Сент-Китс и Невис', phone: '1-869' },
    {
      code: 'KP',
      label: 'Корейская Народно-Демократическая Республика',
      phone: '850',
    },
    { code: 'KR', label: 'Республика Корея', phone: '82' },
    { code: 'KW', label: 'Кувейт', phone: '965' },
    { code: 'KY', label: 'Каймановы острова', phone: '1-345' },
    { code: 'KZ', label: 'Казахстан', phone: '7' },
    {
      code: 'LA',
      label: 'Лаос, Народно-Демократическая Республика',
      phone: '856',
    },
    { code: 'LB', label: 'Ливан', phone: '961' },
    { code: 'LC', label: 'Сент-Люсия', phone: '1-758' },
    { code: 'LI', label: 'Лихтенштейн', phone: '423' },
    { code: 'LK', label: 'Шри-Ланка', phone: '94' },
    { code: 'LR', label: 'Либерия', phone: '231' },
    { code: 'LS', label: 'Лесото', phone: '266' },
    { code: 'LT', label: 'Литва', phone: '370' },
    { code: 'LU', label: 'Люксембург', phone: '352' },
    { code: 'LV', label: 'Латвия', phone: '371' },
    { code: 'LY', label: 'Ливия', phone: '218' },
    { code: 'MA', label: 'Марокко', phone: '212' },
    { code: 'MC', label: 'Монако', phone: '377' },
    { code: 'MD', label: 'Молдова, Республика', phone: '373' },
    { code: 'ME', label: 'Черногория', phone: '382' },
    { code: 'MF', label: 'Сен-Мартен (французская часть)', phone: '590' },
    { code: 'MG', label: 'Мадагаскар', phone: '261' },
    { code: 'MH', label: 'Маршалловы острова', phone: '692' },
    {
      code: 'MK',
      label: 'Македония, бывшая Югославская Республика',
      phone: '389',
    },
    { code: 'ML', label: 'Мали', phone: '223' },
    { code: 'MM', label: 'Мьянма', phone: '95' },
    { code: 'MN', label: 'Монголия', phone: '976' },
    { code: 'MO', label: 'Макао', phone: '853' },
    { code: 'MP', label: 'Северные Марианские острова', phone: '1-670' },
    { code: 'MQ', label: 'Мартиника', phone: '596' },
    { code: 'MR', label: 'Мавритания', phone: '222' },
    { code: 'MS', label: 'Монтсеррат', phone: '1-664' },
    { code: 'MT', label: 'Мальта', phone: '356' },
    { code: 'MU', label: 'Маврикий', phone: '230' },
    { code: 'MV', label: 'Мальдивы', phone: '960' },
    { code: 'MW', label: 'Малави', phone: '265' },
    { code: 'MX', label: 'Мексика', phone: '52' },
    { code: 'MY', label: 'Малайзия', phone: '60' },
    { code: 'MZ', label: 'Мозамбик', phone: '258' },
    { code: 'NA', label: 'Намибия', phone: '264' },
    { code: 'NC', label: 'Новая Каледония', phone: '687' },
    { code: 'NE', label: 'Нигер', phone: '227' },
    { code: 'NF', label: 'Норфолк', phone: '672' },
    { code: 'NG', label: 'Нигерия', phone: '234' },
    { code: 'NI', label: 'Никарагуа', phone: '505' },
    { code: 'NL', label: 'Нидерланды', phone: '31' },
    { code: 'NO', label: 'Норвегия', phone: '47' },
    { code: 'NP', label: 'Непал', phone: '977' },
    { code: 'NR', label: 'Науру', phone: '674' },
    { code: 'NU', label: 'Ниуэ', phone: '683' },
    { code: 'NZ', label: 'Новая Зеландия', phone: '64' },
    { code: 'OM', label: 'Оман', phone: '968' },
    { code: 'PA', label: 'Панама', phone: '507' },
    { code: 'PE', label: 'Перу', phone: '51' },
    { code: 'PF', label: 'Французская Полинезия', phone: '689' },
    { code: 'PG', label: 'Папуа — Новая Гвинея', phone: '675' },
    { code: 'PH', label: 'Филиппины', phone: '63' },
    { code: 'PK', label: 'Пакистан', phone: '92' },
    { code: 'PL', label: 'Польша', phone: '48' },
    { code: 'PM', label: 'Сен-Пьер и Микелон', phone: '508' },
    { code: 'PN', label: 'Питкэрн', phone: '870' },
    { code: 'PR', label: 'Пуэрто-Рико', phone: '1' },
    { code: 'PS', label: 'Государство Палестина', phone: '970' },
    { code: 'PT', label: 'Португалия', phone: '351' },
    { code: 'PW', label: 'Палау', phone: '680' },
    { code: 'PY', label: 'Парагвай', phone: '595' },
    { code: 'QA', label: 'Катар', phone: '974' },
    { code: 'RE', label: 'Реюньон', phone: '262' },
    { code: 'RO', label: 'Румыния', phone: '40' },
    { code: 'RS', label: 'Сербия', phone: '381' },
    { code: 'RU', label: 'Российская Федерация', phone: '7' },
    { code: 'RW', label: 'Руанда', phone: '250' },
    { code: 'SA', label: 'Саудовская Аравия', phone: '966' },
    { code: 'SB', label: 'Соломоновы острова', phone: '677' },
    { code: 'SC', label: 'Сейшельские острова', phone: '248' },
    { code: 'SD', label: 'Судан', phone: '249' },
    { code: 'SE', label: 'Швеция', phone: '46' },
    { code: 'SG', label: 'Сингапур', phone: '65' },
    { code: 'SH', label: 'Остров Святой Елены', phone: '290' },
    { code: 'SI', label: 'Словения', phone: '386' },
    { code: 'SJ', label: 'Шпицберген и Ян-Майен', phone: '47' },
    { code: 'SK', label: 'Словакия', phone: '421' },
    { code: 'SL', label: 'Сьерра-Леоне', phone: '232' },
    { code: 'SM', label: 'Сан-Марино', phone: '378' },
    { code: 'SN', label: 'Сенегал', phone: '221' },
    { code: 'SO', label: 'Сомали', phone: '252' },
    { code: 'SR', label: 'Суринам', phone: '597' },
    { code: 'SS', label: 'Южный Судан', phone: '211' },
    { code: 'ST', label: 'Сан-Томе и Принсипи', phone: '239' },
    { code: 'SV', label: 'Сальвадор', phone: '503' },
    { code: 'SX', label: 'Синт-Мартен (голландская часть)', phone: '1-721' },
    { code: 'SY', label: 'Сирийская Арабская Республика', phone: '963' },
    { code: 'SZ', label: 'Свазиленд', phone: '268' },
    { code: 'TC', label: 'Теркс и Кайкос', phone: '1-649' },
    { code: 'TD', label: 'Чад', phone: '235' },
    { code: 'TF', label: 'Французские южные территории', phone: '262' },
    { code: 'TG', label: 'Того', phone: '228' },
    { code: 'TH', label: 'Таиланд', phone: '66' },
    { code: 'TJ', label: 'Таджикистан', phone: '992' },
    { code: 'TK', label: 'Токелау', phone: '690' },
    { code: 'TL', label: 'Восточный Тимор', phone: '670' },
    { code: 'TM', label: 'Туркменистан', phone: '993' },
    { code: 'TN', label: 'Тунис', phone: '216' },
    { code: 'TO', label: 'Тонга', phone: '676' },
    { code: 'TR', label: 'Турция', phone: '90' },
    { code: 'TT', label: 'Тринидад и Тобаго', phone: '1-868' },
    { code: 'TV', label: 'Тувалу', phone: '688' },
    { code: 'TW', label: 'Тайвань, Китайская Республика', phone: '886' },
    { code: 'TZ', label: 'Объединенная Республика Танзания', phone: '255' },
    { code: 'UA', label: 'Украина', phone: '380' },
    { code: 'UG', label: 'Уганда', phone: '256' },
    { code: 'US', label: 'Соединенные Штаты', phone: '1', suggested: true },
    { code: 'UY', label: 'Уругвай', phone: '598' },
    { code: 'UZ', label: 'Узбекистан', phone: '998' },
    { code: 'VA', label: 'Святой Престол (Государство Ватикан)', phone: '379' },
    { code: 'VC', label: 'Сент-Винсент и Гренадины', phone: '1-784' },
    { code: 'VE', label: 'Венесуэла', phone: '58' },
    { code: 'VG', label: 'Британские Виргинские острова', phone: '1-284' },
    { code: 'VI', label: 'Американские Виргинские острова', phone: '1-340' },
    { code: 'VN', label: 'Вьетнам', phone: '84' },
    { code: 'VU', label: 'Вануату', phone: '678' },
    { code: 'WF', label: 'Уоллис и Футуна', phone: '681' },
    { code: 'WS', label: 'Самоа', phone: '685' },
    { code: 'XK', label: 'Косово', phone: '383' },
    { code: 'YE', label: 'Йемен', phone: '967' },
    { code: 'YT', label: 'Майотта', phone: '262' },
    { code: 'ZA', label: 'Южная Африка', phone: '27' },
    { code: 'ZM', label: 'Замбия', phone: '260' },
    { code: 'ZW', label: 'Зимбабве', phone: '263' },
  ]